# Generated by Django 5.1 on 2024-09-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magnetJobs', '0002_remove_users_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='display_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
