# Generated by Django 5.1 on 2024-11-07 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magnetJobs', '0005_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.TextField(default='confirmación-amistad'),
        ),
    ]
