# Generated by Django 5.1 on 2024-11-07 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magnetJobs', '0006_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.TextField(default='notificacion'),
        ),
    ]
